server:
  port: 8888

spring:
  application:
    name: blog-config-center
#配置中心
  cloud:
    config: 
      server: 
        native:
          search-locations: classpath:/configs/{profile}
#         searchLocations: file:/d:/configs/{profile}
        git:
          uri: https://gitee.com/yy1122/SpringcloudConfigs
          default-label: master
          search-paths: '{profile}' 
          username: 1396513066@qq.com
          password: password

#注册到服务中心    
eureka:
  instance:
    hostname: localhost
  client:
  #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    registry-fetch-interval-seconds: 5
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://eureka:woaini123@localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always   