server:
  port: 9800
logging: 
  level: 
    root: info
    cn.oauth2: debug
  file: blog-oauth2-log/access.log
spring:
  security:
    oauth2:
      client_secret: admin   
  application:
    name: blog-oauth2-center
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    servlet:
      load-on-startup: 1
#mybatis
mybatis: 
  mapper-locations: classpath:/mapper/*
  configuration:
    mapUnderscoreToCamelCase: true
ribbon: 
  ReadTimeout: 10000
  ConnectTimeout: 10000
 #注入到服务中心
eureka:
  instance:
    hostname: 127.0.0.1
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    serviceUrl: 
      defaultZone: http://test:123@127.0.0.1:8761/eureka/ 
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always     
access_token: 
  store-jwt: false
  jwt-secret: (your-jwt-secret:)(^_^)(your-jwt-secret:)