#端口
server:
  port: 8761
 
#服务名 
spring:
  application:
    name: blog-register-center

#注册中心安全保护    
  security:
    user:
      name: test
      password: 123
    
eureka: 
  instance:
    hostname: 127.0.0.1
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: false
    health-check-url-path: /actuator/health
    metadata-map: 
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: false
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always      