#端口
server: 
  port: 0
  
spring:
  application:
    name: blog-file-center
 
#alibaba oss
oss: 
  aliyun: 
    bucketName: triedblog
    endpoint: http://oss-cn-beijing.aliyuncs.com
    accessKeyId: accessKeyId
    secretAccessKey: secretAccessKey
#security
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:9800/check_user
      prefer-token-info: false
#注入到服务中心
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://test:123@127.0.0.1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always